### PR TITLE
fix: string arguments

### LINKED ISSUE #2103: String arguments need weird double quote combination to work: '"<string>"'
In order to instantiate a contract with argument String I need to wrap the string in the terminal with `'"`, example: 
`--args '"argument"'`

### PR DESCRIPTION
**Pull request by Daanvdplas**
Allows to provide strings like:

  - ✅ --args daan - Simple unquoted string
  - ✅ --args "daan van der plas" - String with spaces
  - ✅ --args "John Paul" "von Neumann" - Multiple strings with spaces
  - ✅ --args '"alice"' - Old syntax still works (backward compatible)
  
  Closes #2103

### CODE REVIEW

File: crates/transcode/src/lib.rs [hunk 1]
```diff
@@ -618,6 +669,11 @@ mod tests {
             pub fn h160(&self, addr: ink::H160) {
                 let _ = addr;
             }
+
+            #[ink(message)]
+            pub fn set_name(&self, name: String) {
+                let _ = name;
```
Comment (cmichi) [inline crates/transcode/src/lib.rs]:
```suggestion
            pub fn set_name(&self, _name: String) {
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,8 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 [Unreleased]
 
+- Accept plain string call arguments by inferring types from metadata - [2161](https://github.com/use-ink/cargo-contract/pull/2161).
```
Comment (Daanvdplas) [inline CHANGELOG.md]:
```suggestion
### Fixed
- Accept plain string call arguments by inferring types from metadata - [2161](https://github.com/use-ink/cargo-contract/pull/2161).
```
