### PR TITLE
Skip linting if running building in --offline mode

### LINKED ISSUE #732: The flag `--offline` is broken in newest `cargo-contract` version
On cargo-contract 2.0.0-alpha.2, when trying to build a ink! Smart Contract with the `--offline` flag and without internet connection, `cargo-contract` still tries to reach out to a server to check linting rules:

```shell
root@cca06f948add:/builds/contract# cargo contract --version
cargo-contract 2.0.0-alpha.2-77f53dd-x86_64-unknown-linux-gnu
root@cca06f948add:/builds/contract# cargo contract build --offline
 [1/6] Checking ink! linting rules
If you don't see a backtrace below, it could be because `cargo-dylint` wasn't built with a nightly compiler.
Error: Could not find `--lib ink_linting`
ERROR: `"/usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "dylint" "--lib=ink_linting" "--quiet"` failed with exit code: Some(1)
root@cca06f948add:/builds/contract# 
```

### PR DESCRIPTION
**Pull request by ascjones**
Fixes #732.

Skips the linting step if building with `--offline`. This is because `cargo dylint` requires network access to build the linting drivers.

### CODE REVIEW

File: crates/cargo-contract/src/cmd/build/mod.rs [hunk 1]
```diff
@@ -188,6 +188,8 @@ impl BuildCommand {
             false => Network::Online,
         };
 
+        let skip_linting = self.skip_linting || matches!(network, Network::Offline);
```
Comment (HCastano) [inline crates/cargo-contract/src/cmd/build/mod.rs:191]: I'd add a comment as to why we skip linting in this case

**Review by HCastano — APPROVED** [review]

File: crates/cargo-contract/src/cmd/build/mod.rs [hunk 2]
```diff
@@ -188,6 +188,8 @@ impl BuildCommand {
             false => Network::Online,
         };
 
+        // The nvocation of `cargo dylint` requires network access, so in offline mode the linting
```
Comment (HCastano) [inline crates/cargo-contract/src/cmd/build/mod.rs:191]:
```suggestion
        // The invocation of `cargo dylint` requires network access, so in offline mode the linting
```
