### PR TITLE
Fix parsing of docker STDOUT

### LINKED ISSUE #1455: Unable to build a verifiable ink! flipper contract
**Describe the bug**

When trying to execute a verifiable build locally for the [flipper contract](https://github.com/paritytech/ink-examples/tree/main/flipper) from [ink-examples](https://github.com/paritytech/ink-examples) project, I face the following error:

```bash
cargo contract build --verifiable
 [==] Started the build inside the container: ink-verified-flipper-63196
 [==] Checking clippy linting rules
error: 'cargo-clippy' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'
To install, run `rustup component add clippy`
 [==] Building cargo project
    Building...
    Building [=========================> ] 86/87: flipper(bin)
    Finished release [optimized] target(s) in 2m 33s
 [==] Post processing code
 [==] Generating metadata
   Compiling...
    Finished release [optimized] target(s) in 5m 52s
    Running `target/ink/release/metadata-gen`
 [==] Generating bundle
ERROR: Error decoding BuildResult:
 }

Caused by:
    expected value at line 1 column 1
```

**To Reproduce**
1. Build the [flipper contract](https://github.com/paritytech/ink-examples/tree/main/flipper) with the --verifiable flag:

`cargo contract build --verifiable`

**Expected behavior**
The expected response should contain metadata with the `paritytech/contracts-verifiable` image according to the [documentation](https://use.ink/basics/verification/contract-verification).

**Environment (please complete the following information):**
 - OS: MacOS M1 darwin
 - rust: 1.72.1
 - rust toolchain: 1.72-aarch64-apple-darwin
 - `cargo-contract` version: 4.0.0-rc.1
 - ink! version: 4.2.0

**Additional context**

I don't think the clippy error cause this issue since I also tried overriding the `paritytech/contracts-verifiable` image with clippy installed.

### PR DESCRIPTION
**Pull request by SkymanOne**
## Summary
Closes #1455
- [ ] y/n | Does it introduce breaking changes?
- [ ] y/n | Is it dependent on the specific version of `ink` or `pallet-contracts`?

It was previously common to see the following error at the end of a verifiable build, even when the build was successful:
image

The previous implementation expected the `BuildResult` to be sent in a stream as a whole chunk of bytes. However, there can be cases when the data is sent in multiple chunks, which results in incorrect parsing.

We simply collect the byte chunks and then attempt to decode them together.

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have added an entry to `CHANGELOG.md`
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: crates/build/src/docker.rs [hunk 1]
```diff
@@ -414,17 +414,11 @@ async fn run_build(
     let stderr = std::io::stderr();
     let mut stderr = stderr.lock();
     let mut build_result = None;
+    let mut build_bytes: Vec<u8> = vec![];
```
Comment (smiasojed) [inline crates/build/src/docker.rs:417]: I think `stdout_message` would be a better fit here.

Comment (ascjones) [inline crates/build/src/docker.rs]: Maybe a better name would be something like `stdout_bytes/buffer`

**Review by ascjones — APPROVED** [review]

**Comment by smiasojed** [comment]
I think it would be great to have a CI test, which could catch issues like this.

**Comment by SkymanOne** [comment]
> I think it would be great to have a CI test, which could catch issues like this.

The problem is that we need to have a nested docker environment. Idk if it's possible to run docker container inside another container.

**Comment by smiasojed** [comment]
> > I think it would be great to have a CI test, which could catch issues like this.
> 
> The problem is that we need to have a nested docker environment. Idk if it's possible to run docker container inside another container.

I do not see any docker image used for CI, it seems that we are building this directly on the runner

**Comment by SkymanOne** [comment]
> > > I think it would be great to have a CI test, which could catch issues like this.
> > 
> > 
> > The problem is that we need to have a nested docker environment. Idk if it's possible to run docker container inside another container.
> 
> I do not see any docker image used for CI, it seems that we are building this directly on the runner

Sure, I'll do it in the follow up PR then

**Review by smiasojed — APPROVED** [review]

**Comment by cmichi** [comment]
> Sure, I'll do it in the follow up PR then

@SkymanOne Please create a GitHub issue for it and assign it to yourself.

**Review by cmichi — APPROVED** [review]
