### PR TITLE
Fix linting support on Apple Silicon

### LINKED ISSUE #478: Error: Could not find --lib ink_linting
I get this error when I try to run the `cargo contract build` command:

```
Error: Could not find `--lib ink_linting`
ERROR: `"/Users/name/.rustup/toolchains/nightly-2021-12-05-aarch64-apple-darwin/bin/cargo" "dylint" "--lib" "ink_linting" "--manifest-path=/Users/name/Code/Rust/project/Cargo.toml"` failed with exit code: Some(1)
```

I have already run: 
```
cargo install cargo-dylint dylint-link
cargo install --force cargo-contract
````

### PR DESCRIPTION
**Pull request by athei**
Fixes #478

Apple Silicon wasn't defined in the `config.toml` of our linting project. And hence `dylint-link` wasn't used to produce the binary. I also added a hand full of other common architectures.

This won't fix the windows CI, though. I am not sure what is up with that.

### CODE REVIEW

File: build.rs [hunk 1]
```diff
@@ -329,9 +332,15 @@ fn zip_dylint_driver(src_dir: &Path, dst_file: &Path, method: CompressionMethod)
             buffer.clear();
 
             zip.finish()?;
+            lib_found = true;
             break;
         }
     }
+
+    if !lib_found {
+        anyhow::bail!("Couldn't find compiled lint. Is your architecture defined in ./ink_linting/.cargo/config.toml?");
```
Comment (cmichi) [inline build.rs:341]: Could you include the architecture here in the bail message? Makes debugging easier.

**Comment by cmichi** [comment]
@athei I've created [this debugging PR](https://github.com/paritytech/cargo-contract/pull/490) based on yours. For Windows there are two files in the folder: `ink_linting.dll` and `ink_linting@nightly-2021-11-04-x86_64-pc-windows-msvc.dll`. No `libink_linting@…` though. Maybe that's why the Windows CI fails?

https://github.com/paritytech/cargo-contract/runs/5827726812?check_suite_focus=true#step:8:1103

**Comment by cmichi** [comment]
@athei The CI runs through on my debugging PR, so I think if you copy the `regex` change over it should be fine.

**Review by cmichi — APPROVED** [review]
Great that you found it!
