### PR TITLE
fix: event decoding

### LINKED ISSUE #2150: fix: decode event values
**Describe the bug**
For a contract event, cargo contract is not properly decoding the value

**To Reproduce**
Use a contract with events, or I just have added a simple event in Flipper contract:
```rs
#[ink(event)]
    pub struct Test {
        value: bool,
    }
```
And emit it once calling the `flip` message:
```rs
#[ink(message)]
        pub fn flip(&mut self) {
            self.value = !self.value;
            Self::env().emit_event(Test {
                value: self.value,
            });
        }
```

The output from cargo-contract is:
```
Event Revive ➜ ContractEmitted
         contract: 0x5801b439a678d9d3a68b8019da6a4abfa507de11
         data: 0x040004882e8db2d778ca9655ea3223def2503a484e55d21aaec3485fef87b8fbadbf29
         topics: 0x040004882e8db2d778ca9655ea3223def2503a484e55d21aaec3485fef87b8fbadbf29
```

The data should be decoded into the event.

### PR DESCRIPTION
**Pull request by Daanvdplas**
Closes #2150

### CODE REVIEW

File: crates/extrinsics/src/events.rs [hunk 1]
```diff
@@ -181,25 +181,66 @@ impl DisplayEvents {
...
-            let event_sig_topic = event.topics().iter().next();
             let mut unnamed_field_name = 0;
             for field_metadata in event_fields {
-                if <ContractEmitted as StaticEvent>::is_event(
-                    event.pallet_name(),
-                    event.variant_name(),
-                ) && (field_metadata.name == Some("data".to_string())
-                    || field_metadata.name == Some("topics".to_string()))
-                {
-                    tracing::debug!("event data: {:?}", hex::encode(&event_data));
```
Comment (cmichi) [inline crates/extrinsics/src/events.rs]: Can you retain the
```
tracing::debug!("event data: {:?}", hex::encode(&event_data));
```
? Just put it right below `let event_data`.
